//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBedsIntegration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingConfirmation
    {
        public int ID { get; set; }
        public string Reference { get; set; }
        public string clientReference { get; set; }
        public string CreationData { get; set; }
        public string Status { get; set; }
        public string cancellationPolicy { get; set; }
        public string modificationPolicy { get; set; }
        public string CreationUser { get; set; }
        public string HolderName { get; set; }
        public string HolderSurName { get; set; }
        public string BookingNum { get; set; }
        public string SessionID { get; set; }
        public string supplier { get; set; }
        public string Remark { get; set; }
        public string invoiceCompany { get; set; }
        public string invoiceCompanyCode { get; set; }
        public string RegistrationNumber { get; set; }
        public string totalAmount { get; set; }
        public string Currency { get; set; }
        public string PendingAmount { get; set; }
        public string response { get; set; }
    }
}
