//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBedsIntegration.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelBedEntity : DbContext
    {
        public HotelBedEntity()
            : base("name=HotelBedEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailabilityRequest> AvailabilityRequests { get; set; }
        public virtual DbSet<AvailabilityResponse> AvailabilityResponses { get; set; }
        public virtual DbSet<BookingConfirmation> BookingConfirmations { get; set; }
        public virtual DbSet<BookingRequest> BookingRequests { get; set; }
        public virtual DbSet<BookingRoom> BookingRooms { get; set; }
        public virtual DbSet<Pax> Paxes { get; set; }
        public virtual DbSet<PolicyBooking> PolicyBookings { get; set; }
        public virtual DbSet<RequestPAX> RequestPAXES { get; set; }
        public virtual DbSet<RoomPolicy> RoomPolicies { get; set; }
        public virtual DbSet<RoomTax> RoomTaxes { get; set; }
        public virtual DbSet<SearchHotelData> SearchHotelDatas { get; set; }
        public virtual DbSet<SearchRequest> SearchRequests { get; set; }
        public virtual DbSet<SearchRoom> SearchRooms { get; set; }
    }
}
