//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBedsIntegration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchHotelData
    {
        public int Id { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> Code { get; set; }
        public string Name { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string destinationCode { get; set; }
        public string DestinationName { get; set; }
        public string ZoneCode { get; set; }
        public string ZoneName { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string minRate { get; set; }
        public string maxRate { get; set; }
        public string currency { get; set; }
        public string checkIn { get; set; }
        public string checkOut { get; set; }
        public string total { get; set; }
        public string Request { get; set; }
    }
}
