//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBedsIntegration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilityResponse
    {
        public int ID { get; set; }
        public string SearchID { get; set; }
        public Nullable<int> SearchHotelID { get; set; }
        public string TotalPrice { get; set; }
        public string Currency { get; set; }
        public string response { get; set; }
    }
}
