//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBedsIntegration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingRoom
    {
        public int ID { get; set; }
        public string SearchId { get; set; }
        public string RId { get; set; }
        public string Name { get; set; }
        public string code { get; set; }
        public string rateClass { get; set; }
        public string Net { get; set; }
        public string sellingRate { get; set; }
        public string hotelMandatory { get; set; }
        public string rateComments { get; set; }
        public string paymentType { get; set; }
        public string packaging { get; set; }
        public string boardCode { get; set; }
        public string boardName { get; set; }
        public Nullable<int> rooms { get; set; }
        public Nullable<int> Adult { get; set; }
        public Nullable<int> Child { get; set; }
        public Nullable<int> BookingID { get; set; }
    }
}
