//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBedsIntegration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchRoom
    {
        public int Id { get; set; }
        public string RoomCode { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> SearchHotelID { get; set; }
        public string ResponseType { get; set; }
        public string rateKey { get; set; }
        public string rateClass { get; set; }
        public string rateType { get; set; }
        public string netPrice { get; set; }
        public string sellingRate { get; set; }
        public string hotelMandatory { get; set; }
        public Nullable<int> allotment { get; set; }
        public string paymentType { get; set; }
        public string packaging { get; set; }
        public string boardCode { get; set; }
        public string boardName { get; set; }
        public Nullable<int> rooms { get; set; }
        public Nullable<int> adults { get; set; }
        public Nullable<int> children { get; set; }
        public string childrenAges { get; set; }
        public string sessionID { get; set; }
    }
}
