//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class availabilityRoomRe
    {
        public int id { get; set; }
        public string BookingNum { get; set; }
        public string Sid { get; set; }
        public Nullable<int> RoomCode { get; set; }
        public string RoomRef { get; set; }
        public string Pid { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public string Courrency { get; set; }
        public Nullable<int> roomId { get; set; }
    }
}
