//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilityRe
    {
        public int id { get; set; }
        public string Sid { get; set; }
        public string BookingNum { get; set; }
        public int Status { get; set; }
        public Nullable<double> OldTotalcost { get; set; }
        public Nullable<double> NewTotalcost { get; set; }
        public Nullable<double> TotalsellPrice { get; set; }
        public string SellCurrency { get; set; }
        public string PID { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string hotelCode { get; set; }
    }
}
