//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BusinessRulesDBEntities : DbContext
    {
        public BusinessRulesDBEntities()
            : base("name=BusinessRulesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChargeType> ChargeTypes { get; set; }
        public virtual DbSet<Criterias_Difinition> Criterias_Difinition { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<DailyCurrency> DailyCurrencies { get; set; }
        public virtual DbSet<EveryDayCurrenciesConversion> EveryDayCurrenciesConversions { get; set; }
        public virtual DbSet<FormOfPayment> FormOfPayments { get; set; }
        public virtual DbSet<HistoryDailyCurrency> HistoryDailyCurrencies { get; set; }
        public virtual DbSet<HotelProvider> HotelProviders { get; set; }
        public virtual DbSet<PointOfSale> PointOfSales { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<ProvidersCurrency> ProvidersCurrencies { get; set; }
        public virtual DbSet<RelatedUnit> RelatedUnits { get; set; }
        public virtual DbSet<SalesDiscountCriteria> SalesDiscountCriterias { get; set; }
        public virtual DbSet<SalesDiscount> SalesDiscounts { get; set; }
        public virtual DbSet<SalesMarkupCriteria> SalesMarkupCriterias { get; set; }
        public virtual DbSet<SalesMarkup> SalesMarkups { get; set; }
        public virtual DbSet<SalesRulesFlightOption> SalesRulesFlightOptions { get; set; }
        public virtual DbSet<SourceTraffic> SourceTraffics { get; set; }
    
        public virtual ObjectResult<GetActiveProviders_Result> GetActiveProviders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveProviders_Result>("GetActiveProviders");
        }
    }
}
