//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancellationRoom
    {
        public int Id { get; set; }
        public string BookingNum { get; set; }
        public string reference { get; set; }
        public string RoomStatus { get; set; }
        public string RoomName { get; set; }
        public string supplierReference { get; set; }
        public string code { get; set; }
        public string rateClass { get; set; }
        public string net { get; set; }
        public string hotelMandatory { get; set; }
        public string boardName { get; set; }
        public string adults { get; set; }
        public string children { get; set; }
        public string Paxes { get; set; }
    }
}
