//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancellationBooking
    {
        public int id { get; set; }
        public string Reference { get; set; }
        public string CancellationReference { get; set; }
        public string ClientReference { get; set; }
        public string creationDate { get; set; }
        public string Cancelstatus { get; set; }
        public string creationUser { get; set; }
        public string HolderFirstName { get; set; }
        public string HolderLastName { get; set; }
        public string checkOut { get; set; }
        public string checkIn { get; set; }
        public string HotelCode { get; set; }
        public string totalNet { get; set; }
        public string Currency { get; set; }
        public string CancellationAmount { get; set; }
        public string SupplierName { get; set; }
        public string VatNumber { get; set; }
        public string InvoiceCompany { get; set; }
        public string InvoiceCompanyCode { get; set; }
        public string CompanyregistrationNum { get; set; }
        public string BookingTotalNet { get; set; }
        public string BookingCurrency { get; set; }
        public string cancellationFlag { get; set; }
        public string BookingNum { get; set; }
        public string BookingReference { get; set; }
    }
}
