//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckAvailability
    {
        public int ID { get; set; }
        public string sID { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string HotelCode { get; set; }
        public string RoomCode { get; set; }
        public Nullable<double> OldCost { get; set; }
        public Nullable<double> NewCost { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
