//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityTourismTax
    {
        public int ID { get; set; }
        public string CityID { get; set; }
        public string Type { get; set; }
        public Nullable<double> Value { get; set; }
        public string Currency { get; set; }
        public Nullable<int> StarRating { get; set; }
    }
}
