//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmationRequest
    {
        public int id { get; set; }
        public string BookingNum { get; set; }
        public string Sessionid { get; set; }
        public string Status { get; set; }
    }
}
