//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class countriesID
    {
        public int ID { get; set; }
        public string providerCountry { get; set; }
        public Nullable<int> providerID { get; set; }
        public string countryID { get; set; }
    }
}
