//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string phoneCode { get; set; }
        public string region { get; set; }
        public string regionCode { get; set; }
        public string name_Ar { get; set; }
        public string region_Ar { get; set; }
        public string CountryCode { get; set; }
    }
}
