//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string Customer_User_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Phone_Code { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Passport_No { get; set; }
        public string Gender { get; set; }
        public string Salutations { get; set; }
        public Nullable<System.DateTime> Passport_Expiration_Date { get; set; }
    }
}
