//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyCurrency
    {
        public int ID { get; set; }
        public string FromCurrency { get; set; }
        public string ToCurrency { get; set; }
        public System.DateTime DateTime { get; set; }
        public double Customer_Purchase_Rate { get; set; }
        public double Customer_Sell_Rate { get; set; }
        public double Supplier_Purchase_Rate { get; set; }
        public double Supplier_Sell_Rate { get; set; }
        public string Date { get; set; }
    }
}
