//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelsTransportation
    {
        public int ID { get; set; }
        public string HotelID { get; set; }
        public string TransportationType { get; set; }
        public string TransportationName { get; set; }
        public Nullable<double> Dist { get; set; }
        public string DistUnit { get; set; }
        public Nullable<double> DistTime { get; set; }
        public string DistTimeUnit { get; set; }
        public string Directions { get; set; }
    }
}
