//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public int ID { get; set; }
        public string builtYear { get; set; }
        public string renovationyear { get; set; }
        public string countryName { get; set; }
        public string countryCode { get; set; }
        public Nullable<int> runno { get; set; }
        public Nullable<int> floors { get; set; }
        public Nullable<int> noOfRooms { get; set; }
        public string Luxury { get; set; }
        public string hotelName { get; set; }
        public string address { get; set; }
        public string zipCode { get; set; }
        public string location { get; set; }
        public string locationID { get; set; }
        public string location1 { get; set; }
        public string location2 { get; set; }
        public string location3 { get; set; }
        public string cityName { get; set; }
        public string cityCode { get; set; }
        public string stateName { get; set; }
        public string stateCode { get; set; }
        public string regionName { get; set; }
        public string regionCode { get; set; }
        public string hotelPhone { get; set; }
        public string hotelCheckIN { get; set; }
        public string hotelCheckOut { get; set; }
        public string minAge { get; set; }
        public string rating { get; set; }
        public string fireSafety { get; set; }
        public string direct { get; set; }
        public string chain { get; set; }
        public string lastUpdate { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string city2 { get; set; }
        public string preferred { get; set; }
        public string hotelID { get; set; }
    }
}
