//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelPackage
    {
        public int id { get; set; }
        public Nullable<int> PackageNum { get; set; }
        public string Hotelid { get; set; }
        public Nullable<int> Provider { get; set; }
        public string Session { get; set; }
        public string Category { get; set; }
        public Nullable<double> PricePerNight { get; set; }
        public Nullable<double> PricePerAllNight { get; set; }
        public string Currency { get; set; }
    }
}
