//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBookingRoom
    {
        public int ID { get; set; }
        public string Booking_No { get; set; }
        public Nullable<int> PID { get; set; }
        public string SID { get; set; }
        public Nullable<int> Room_No { get; set; }
        public string Room_Category { get; set; }
        public string Room_Type { get; set; }
        public string Meal { get; set; }
        public string Special_Request { get; set; }
        public Nullable<int> Paxs_Qty { get; set; }
        public string IsNonRefundable { get; set; }
    }
}
