//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBookingPax
    {
        public int ID { get; set; }
        public string SID { get; set; }
        public string Booking_No { get; set; }
        public Nullable<int> Room_No { get; set; }
        public string Pax_Type { get; set; }
        public string First_name { get; set; }
        public string Last_Name { get; set; }
        public string Salutations { get; set; }
        public string DateOfBirth { get; set; }
        public string Nationality { get; set; }
        public string Phone { get; set; }
        public string Phone_Code { get; set; }
        public Nullable<int> PaxNo { get; set; }
        public Nullable<int> RoomRef { get; set; }
        public bool Lead { get; set; }
    }
}
