//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBookingNight
    {
        public int ID { get; set; }
        public string Booking_No { get; set; }
        public Nullable<System.DateTime> NightDate { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Room_No { get; set; }
        public Nullable<double> Exchange_Rate { get; set; }
    }
}
