//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelProvider
    {
        public int ID { get; set; }
        public Nullable<int> Provider_ID { get; set; }
        public string Provider_Name { get; set; }
        public string Provider_Currency_Code { get; set; }
        public Nullable<bool> Active_Status { get; set; }
    }
}
