//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBookingRoomsStatu
    {
        public int Id { get; set; }
        public string Booking_No { get; set; }
        public Nullable<int> Room_No { get; set; }
        public Nullable<int> Room_Status { get; set; }
        public string Agent_Id { get; set; }
        public string Remark { get; set; }
    }
}
