//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBookingDelivery
    {
        public int Id { get; set; }
        public string Booking_No { get; set; }
        public string Sid { get; set; }
        public string DeliveryId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhoneCode { get; set; }
        public string CustomerPhone { get; set; }
        public System.DateTime BookingTime { get; set; }
        public string BookingStatus { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<double> DeliveryCost { get; set; }
    }
}
