//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotels_Ar
    {
        public int ID { get; set; }
        public string HotelID { get; set; }
        public string countryName { get; set; }
        public string hotelName { get; set; }
        public string address { get; set; }
        public string location { get; set; }
        public string location1 { get; set; }
        public string location2 { get; set; }
        public string location3 { get; set; }
        public string cityName { get; set; }
        public string city2 { get; set; }
    }
}
