//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class hotelsDBEntities : DbContext
    {
        public hotelsDBEntities()
            : base("name=hotelsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apartmentClassification> apartmentClassifications { get; set; }
        public virtual DbSet<BusinessID> BusinessIDs { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CitiesID> CitiesIDs { get; set; }
        public virtual DbSet<CityTax> CityTaxes { get; set; }
        public virtual DbSet<CityTourismTax> CityTourismTaxes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<countriesID> countriesIDs { get; set; }
        public virtual DbSet<hotelAmenitiesID> hotelAmenitiesIDs { get; set; }
        public virtual DbSet<HotelChain> HotelChains { get; set; }
        public virtual DbSet<hotelClassification> hotelClassifications { get; set; }
        public virtual DbSet<HotelLocation> HotelLocations { get; set; }
        public virtual DbSet<HotelRoom> HotelRooms { get; set; }
        public virtual DbSet<hotel> hotels { get; set; }
        public virtual DbSet<Hotels_Ar> Hotels_Ar { get; set; }
        public virtual DbSet<HotelsAmenity> HotelsAmenities { get; set; }
        public virtual DbSet<HotelsDescription> HotelsDescriptions { get; set; }
        public virtual DbSet<HotelsDescriptions_Ar> HotelsDescriptions_Ar { get; set; }
        public virtual DbSet<HotelsImage> HotelsImages { get; set; }
        public virtual DbSet<HotelsLeisure> HotelsLeisures { get; set; }
        public virtual DbSet<HotelsPreference> HotelsPreferences { get; set; }
        public virtual DbSet<hotelsProvider> hotelsProviders { get; set; }
        public virtual DbSet<HotelsTransportation> HotelsTransportations { get; set; }
        public virtual DbSet<InfoType> InfoTypes { get; set; }
        public virtual DbSet<LeisureID> LeisureIDs { get; set; }
        public virtual DbSet<MealsDescription> MealsDescriptions { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<ProvidersNationality> ProvidersNationalities { get; set; }
        public virtual DbSet<ProvidersResidence> ProvidersResidences { get; set; }
        public virtual DbSet<ProvidersSalutation> ProvidersSalutations { get; set; }
        public virtual DbSet<RateBasisID> RateBasisIDs { get; set; }
        public virtual DbSet<roomAmenity> roomAmenities { get; set; }
        public virtual DbSet<SpecialRequestsID> SpecialRequestsIDs { get; set; }
        public virtual DbSet<tmpDotwHotelsRate> tmpDotwHotelsRates { get; set; }
        public virtual DbSet<tmpDotwHotelsRatesTest> tmpDotwHotelsRatesTests { get; set; }
        public virtual DbSet<tmpDotwRoomsCancellation> tmpDotwRoomsCancellations { get; set; }
        public virtual DbSet<tmpDotwRoomsRateDate> tmpDotwRoomsRateDates { get; set; }
        public virtual DbSet<tmpDotwRoomsResult> tmpDotwRoomsResults { get; set; }
        public virtual DbSet<tmpSearchCriteria> tmpSearchCriterias { get; set; }
        public virtual DbSet<tmpTSHotelsRate> tmpTSHotelsRates { get; set; }
        public virtual DbSet<tmpTSRoomsCancelation> tmpTSRoomsCancelations { get; set; }
        public virtual DbSet<tmpTSRoomsRateDate> tmpTSRoomsRateDates { get; set; }
        public virtual DbSet<tmpTSRoomsResult> tmpTSRoomsResults { get; set; }
    
        public virtual int allCountries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("allCountries");
        }
    
        public virtual int DeleteFromTMPDOTWHotelRates(string sID)
        {
            var sIDParameter = sID != null ?
                new ObjectParameter("sID", sID) :
                new ObjectParameter("sID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteFromTMPDOTWHotelRates", sIDParameter);
        }
    
        public virtual int Dotw_Hotels_Rates(string sessionID)
        {
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("sessionID", sessionID) :
                new ObjectParameter("sessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Dotw_Hotels_Rates", sessionIDParameter);
        }
    
        public virtual int Dotw_Hotels_Rates_Async(string sessionID)
        {
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("sessionID", sessionID) :
                new ObjectParameter("sessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Dotw_Hotels_Rates_Async", sessionIDParameter);
        }
    
        public virtual int Dotw_Hotels_Rates_Test(string sessionID)
        {
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("sessionID", sessionID) :
                new ObjectParameter("sessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Dotw_Hotels_Rates_Test", sessionIDParameter);
        }
    
        public virtual int Dotw_Hotels_Rooms_Cancellation(string sessionID)
        {
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("sessionID", sessionID) :
                new ObjectParameter("sessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Dotw_Hotels_Rooms_Cancellation", sessionIDParameter);
        }
    
        public virtual int Dotw_Hotels_Rooms_Rate_Date(string sessionID)
        {
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("sessionID", sessionID) :
                new ObjectParameter("sessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Dotw_Hotels_Rooms_Rate_Date", sessionIDParameter);
        }
    
        public virtual int Dotw_Hotels_Rooms_Results(string sessionID)
        {
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("sessionID", sessionID) :
                new ObjectParameter("sessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Dotw_Hotels_Rooms_Results", sessionIDParameter);
        }
    
        public virtual ObjectResult<GetAllCities_Result> GetAllCities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCities_Result>("GetAllCities");
        }
    
        public virtual ObjectResult<GetAllCountries_Result> GetAllCountries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCountries_Result>("GetAllCountries");
        }
    
        public virtual ObjectResult<GetAllMealCodes_Result> GetAllMealCodes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllMealCodes_Result>("GetAllMealCodes");
        }
    
        public virtual ObjectResult<GetBookItineraryWithBookingNo_Result> GetBookItineraryWithBookingNo(string bookingNo)
        {
            var bookingNoParameter = bookingNo != null ?
                new ObjectParameter("BookingNo", bookingNo) :
                new ObjectParameter("BookingNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBookItineraryWithBookingNo_Result>("GetBookItineraryWithBookingNo", bookingNoParameter);
        }
    
        public virtual ObjectResult<GetCitiesForHotels_Result> GetCitiesForHotels()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCitiesForHotels_Result>("GetCitiesForHotels");
        }
    
        public virtual ObjectResult<GetCityById_Result> GetCityById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCityById_Result>("GetCityById", idParameter);
        }
    
        public virtual ObjectResult<GetCityByName_Result> GetCityByName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCityByName_Result>("GetCityByName", nameParameter);
        }
    
        public virtual ObjectResult<GetCityTaxById_Result> GetCityTaxById(string cityID)
        {
            var cityIDParameter = cityID != null ?
                new ObjectParameter("CityID", cityID) :
                new ObjectParameter("CityID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCityTaxById_Result>("GetCityTaxById", cityIDParameter);
        }
    
        public virtual ObjectResult<GetCityToursimTaxBycityId_Result> GetCityToursimTaxBycityId(string cityid)
        {
            var cityidParameter = cityid != null ?
                new ObjectParameter("Cityid", cityid) :
                new ObjectParameter("Cityid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCityToursimTaxBycityId_Result>("GetCityToursimTaxBycityId", cityidParameter);
        }
    
        public virtual ObjectResult<GetCityToursimTaxBycityIdandRate_Result> GetCityToursimTaxBycityIdandRate(string cityid, Nullable<int> rating)
        {
            var cityidParameter = cityid != null ?
                new ObjectParameter("Cityid", cityid) :
                new ObjectParameter("Cityid", typeof(string));
    
            var ratingParameter = rating.HasValue ?
                new ObjectParameter("Rating", rating) :
                new ObjectParameter("Rating", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCityToursimTaxBycityIdandRate_Result>("GetCityToursimTaxBycityIdandRate", cityidParameter, ratingParameter);
        }
    
        public virtual ObjectResult<GetCounrtyByName_Result> GetCounrtyByName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCounrtyByName_Result>("GetCounrtyByName", nameParameter);
        }
    
        public virtual ObjectResult<GetCountriesForHotels_Result> GetCountriesForHotels()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountriesForHotels_Result>("GetCountriesForHotels");
        }
    
        public virtual ObjectResult<GetCountryByCountryCode_Result> GetCountryByCountryCode(string countryCode)
        {
            var countryCodeParameter = countryCode != null ?
                new ObjectParameter("CountryCode", countryCode) :
                new ObjectParameter("CountryCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountryByCountryCode_Result>("GetCountryByCountryCode", countryCodeParameter);
        }
    
        public virtual ObjectResult<GetCountryById_Result> GetCountryById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountryById_Result>("GetCountryById", idParameter);
        }
    
        public virtual int GetHotelData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetHotelData");
        }
    
        public virtual ObjectResult<GetHotelDataByHotelID_Result> GetHotelDataByHotelID(string providerHotelID, string providerID)
        {
            var providerHotelIDParameter = providerHotelID != null ?
                new ObjectParameter("providerHotelID", providerHotelID) :
                new ObjectParameter("providerHotelID", typeof(string));
    
            var providerIDParameter = providerID != null ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHotelDataByHotelID_Result>("GetHotelDataByHotelID", providerHotelIDParameter, providerIDParameter);
        }
    
        public virtual ObjectResult<GetHotelNameAndHotelId_Result> GetHotelNameAndHotelId(string hotelID, string providerId)
        {
            var hotelIDParameter = hotelID != null ?
                new ObjectParameter("hotelID", hotelID) :
                new ObjectParameter("hotelID", typeof(string));
    
            var providerIdParameter = providerId != null ?
                new ObjectParameter("providerId", providerId) :
                new ObjectParameter("providerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHotelNameAndHotelId_Result>("GetHotelNameAndHotelId", hotelIDParameter, providerIdParameter);
        }
    
        public virtual ObjectResult<string> GetHotelsIdsByCityId(Nullable<int> cityId, string providerID)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var providerIDParameter = providerID != null ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetHotelsIdsByCityId", cityIdParameter, providerIDParameter);
        }
    
        public virtual ObjectResult<GetImagesByHotelID_Result> GetImagesByHotelID(string providerHotelID)
        {
            var providerHotelIDParameter = providerHotelID != null ?
                new ObjectParameter("providerHotelID", providerHotelID) :
                new ObjectParameter("providerHotelID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetImagesByHotelID_Result>("GetImagesByHotelID", providerHotelIDParameter);
        }
    
        public virtual ObjectResult<GetProviderCityandIdBy_Result> GetProviderCityandIdBy(Nullable<int> cityid)
        {
            var cityidParameter = cityid.HasValue ?
                new ObjectParameter("cityid", cityid) :
                new ObjectParameter("cityid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProviderCityandIdBy_Result>("GetProviderCityandIdBy", cityidParameter);
        }
    
        public virtual ObjectResult<GetProviderCityAndIdByCityID_Result> GetProviderCityAndIdByCityID(Nullable<int> cityId)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProviderCityAndIdByCityID_Result>("GetProviderCityAndIdByCityID", cityIdParameter);
        }
    
        public virtual ObjectResult<GetProviderCurrency_Result> GetProviderCurrency()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProviderCurrency_Result>("GetProviderCurrency");
        }
    
        public virtual ObjectResult<GetProviderData_Result> GetProviderData(string providerName)
        {
            var providerNameParameter = providerName != null ?
                new ObjectParameter("ProviderName", providerName) :
                new ObjectParameter("ProviderName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProviderData_Result>("GetProviderData", providerNameParameter);
        }
    
        public virtual ObjectResult<GetProviderSalutation_Nationality_Residence_Result> GetProviderSalutation_Nationality_Residence(string nationality, string residence, Nullable<int> provider, string salutation)
        {
            var nationalityParameter = nationality != null ?
                new ObjectParameter("nationality", nationality) :
                new ObjectParameter("nationality", typeof(string));
    
            var residenceParameter = residence != null ?
                new ObjectParameter("residence", residence) :
                new ObjectParameter("residence", typeof(string));
    
            var providerParameter = provider.HasValue ?
                new ObjectParameter("provider", provider) :
                new ObjectParameter("provider", typeof(int));
    
            var salutationParameter = salutation != null ?
                new ObjectParameter("salutation", salutation) :
                new ObjectParameter("salutation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProviderSalutation_Nationality_Residence_Result>("GetProviderSalutation_Nationality_Residence", nationalityParameter, residenceParameter, providerParameter, salutationParameter);
        }
    
        public virtual ObjectResult<string> GetRoomImageByHotelId(string hotelId)
        {
            var hotelIdParameter = hotelId != null ?
                new ObjectParameter("HotelId", hotelId) :
                new ObjectParameter("HotelId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetRoomImageByHotelId", hotelIdParameter);
        }
    
        public virtual ObjectResult<GetSearchCriteriaBySID_Result> GetSearchCriteriaBySID(string sID)
        {
            var sIDParameter = sID != null ?
                new ObjectParameter("sID", sID) :
                new ObjectParameter("sID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSearchCriteriaBySID_Result>("GetSearchCriteriaBySID", sIDParameter);
        }
    
        public virtual ObjectResult<GetSearchHotelList_Result> GetSearchHotelList(string sID)
        {
            var sIDParameter = sID != null ?
                new ObjectParameter("sID", sID) :
                new ObjectParameter("sID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSearchHotelList_Result>("GetSearchHotelList", sIDParameter);
        }
    
        public virtual ObjectResult<GetSearchHotelListTest_Result> GetSearchHotelListTest(string sID)
        {
            var sIDParameter = sID != null ?
                new ObjectParameter("sID", sID) :
                new ObjectParameter("sID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSearchHotelListTest_Result>("GetSearchHotelListTest", sIDParameter);
        }
    
        public virtual int SaveSearchCriteria(string city, Nullable<System.DateTime> df, Nullable<System.DateTime> dt, Nullable<int> duration, Nullable<int> roomNo, string adults, string children, string infants, string childrenAges, string rateBasis, string residence, string nationality, string sessionID, string pOS)
        {
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var dfParameter = df.HasValue ?
                new ObjectParameter("df", df) :
                new ObjectParameter("df", typeof(System.DateTime));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            var durationParameter = duration.HasValue ?
                new ObjectParameter("duration", duration) :
                new ObjectParameter("duration", typeof(int));
    
            var roomNoParameter = roomNo.HasValue ?
                new ObjectParameter("roomNo", roomNo) :
                new ObjectParameter("roomNo", typeof(int));
    
            var adultsParameter = adults != null ?
                new ObjectParameter("adults", adults) :
                new ObjectParameter("adults", typeof(string));
    
            var childrenParameter = children != null ?
                new ObjectParameter("children", children) :
                new ObjectParameter("children", typeof(string));
    
            var infantsParameter = infants != null ?
                new ObjectParameter("infants", infants) :
                new ObjectParameter("infants", typeof(string));
    
            var childrenAgesParameter = childrenAges != null ?
                new ObjectParameter("childrenAges", childrenAges) :
                new ObjectParameter("childrenAges", typeof(string));
    
            var rateBasisParameter = rateBasis != null ?
                new ObjectParameter("rateBasis", rateBasis) :
                new ObjectParameter("rateBasis", typeof(string));
    
            var residenceParameter = residence != null ?
                new ObjectParameter("residence", residence) :
                new ObjectParameter("residence", typeof(string));
    
            var nationalityParameter = nationality != null ?
                new ObjectParameter("nationality", nationality) :
                new ObjectParameter("nationality", typeof(string));
    
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("sessionID", sessionID) :
                new ObjectParameter("sessionID", typeof(string));
    
            var pOSParameter = pOS != null ?
                new ObjectParameter("POS", pOS) :
                new ObjectParameter("POS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveSearchCriteria", cityParameter, dfParameter, dtParameter, durationParameter, roomNoParameter, adultsParameter, childrenParameter, infantsParameter, childrenAgesParameter, rateBasisParameter, residenceParameter, nationalityParameter, sessionIDParameter, pOSParameter);
        }
    
        public virtual int TS_Hotels_Rates(string sessionID)
        {
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("sessionID", sessionID) :
                new ObjectParameter("sessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TS_Hotels_Rates", sessionIDParameter);
        }
    
        public virtual int TS_Hotels_Rooms_Cancellation(string sessionID)
        {
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("sessionID", sessionID) :
                new ObjectParameter("sessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TS_Hotels_Rooms_Cancellation", sessionIDParameter);
        }
    
        public virtual int TS_Hotels_Rooms_Rate_Date(string sessionID)
        {
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("sessionID", sessionID) :
                new ObjectParameter("sessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TS_Hotels_Rooms_Rate_Date", sessionIDParameter);
        }
    
        public virtual int TS_Hotels_Rooms_Results(string sessionID)
        {
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("sessionID", sessionID) :
                new ObjectParameter("sessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TS_Hotels_Rooms_Results", sessionIDParameter);
        }
    
        public virtual ObjectResult<GetHotelsIDAndProvidersByCityName_Result> GetHotelsIDAndProvidersByCityName(string city)
        {
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHotelsIDAndProvidersByCityName_Result>("GetHotelsIDAndProvidersByCityName", cityParameter);
        }
    
        public virtual ObjectResult<GetHotelsIdsByCityName_Result> GetHotelsIdsByCityName(string city)
        {
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHotelsIdsByCityName_Result>("GetHotelsIdsByCityName", cityParameter);
        }
    }
}
