//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelsAmenity
    {
        public int ID { get; set; }
        public string hotelID { get; set; }
        public string amenitieID { get; set; }
        public string amenitie { get; set; }
        public string amenitie_Ar { get; set; }
        public string Logo { get; set; }
        public string Status { get; set; }
    }
}
