//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvidersNationality
    {
        public int ID { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> provider { get; set; }
        public string providerNationality { get; set; }
    }
}
