//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderSession
    {
        public int ID { get; set; }
        public string PSession { get; set; }
        public Nullable<int> PID { get; set; }
        public string SearchId { get; set; }
        public Nullable<int> Adult { get; set; }
        public Nullable<int> Child { get; set; }
        public Nullable<int> RoomRef { get; set; }
        public string ChildAges { get; set; }


    }
}
