//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public int ID { get; set; }
        public string providerName { get; set; }
        public string providerShortcut { get; set; }
        public string providerUserID { get; set; }
        public string providerPassword { get; set; }
        public string providerCompanyCode { get; set; }
        public string providerDbSource { get; set; }
        public string providerDbDataFile { get; set; }
        public string providerPhone { get; set; }
        public string providerEmail { get; set; }
        public string providerEndPoint { get; set; }
        public string providerDocumentationLink { get; set; }
        public string providerDocumentationType { get; set; }
        public string providerWebsite { get; set; }
        public string providerDescription { get; set; }
        public string providerCurrencyCode { get; set; }
    }
}
