//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMarkup
    {
        public int ID { get; set; }
        public string MarkupName { get; set; }
        public string MarkupBranch { get; set; }
        public string MarkupProduct { get; set; }
        public string CommType { get; set; }
        public Nullable<double> CommAmt { get; set; }
        public string CommRelatedUnit { get; set; }
        public string CommRound { get; set; }
        public Nullable<int> MarkupPriority { get; set; }
        public Nullable<int> ChargeId { get; set; }
        public string MarkupBase { get; set; }
        public Nullable<bool> MarkupStatus { get; set; }
        public Nullable<System.DateTime> MarkupStartDate { get; set; }
        public Nullable<System.DateTime> MarkupEndDate { get; set; }
        public string MarkUpType { get; set; }
    }
}
