//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMarkupCriteria
    {
        public int ID { get; set; }
        public string MarkupID { get; set; }
        public string MarkupCriteria { get; set; }
        public string CriteriaValue { get; set; }
        public string CriteriaValueText { get; set; }
        public string operation { get; set; }
    }
}
