//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDiscount
    {
        public int ID { get; set; }
        public string DiscountName { get; set; }
        public string DiscountBranch { get; set; }
        public string DiscountProduct { get; set; }
        public string CommType { get; set; }
        public Nullable<double> CommAmt { get; set; }
        public string CommRelatedUnit { get; set; }
        public string CommRound { get; set; }
        public Nullable<int> DiscountPriority { get; set; }
        public Nullable<int> ChargeId { get; set; }
        public string DiscountBase { get; set; }
        public Nullable<bool> DiscountStatus { get; set; }
        public Nullable<System.DateTime> DiscountStartDate { get; set; }
        public Nullable<System.DateTime> DiscountEndDate { get; set; }
    }
}
