//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchRoomData
    {
        public int Id { get; set; }
        public string sID { get; set; }
        public Nullable<int> roomNo { get; set; }
        public Nullable<int> adultNo { get; set; }
        public Nullable<int> childernNo { get; set; }
        public string childAge { get; set; }
    }
}
