//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchCriteria
    {
        public int ID { get; set; }
        public string cityName { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> roomNo { get; set; }
        public string passengerNationality { get; set; }
        public string pos { get; set; }
        public string sID { get; set; }
        public Nullable<System.DateTime> sessionCreatedAt { get; set; }
        public string currency { get; set; }
        public string language { get; set; }
        public string source { get; set; }
    }
}
