//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchRoomResult
    {
        public int ID { get; set; }
        public string sID { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string HotelCode { get; set; }
        public string RoomCode { get; set; }
        public string RoomReference { get; set; }
        public Nullable<double> costPrice { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public string SellCurrency { get; set; }
        public Nullable<int> MarkupId { get; set; }
        public Nullable<double> MarkupVal { get; set; }
        public Nullable<int> DiscountId { get; set; }
        public Nullable<double> DiscountVal { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string meal { get; set; }
        public Nullable<int> PaxSQty { get; set; }
        public string roomType { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> Adults { get; set; }
        public Nullable<int> Childern { get; set; }
        public string MealId { get; set; }
        public Nullable<bool> IsRefundable { get; set; }
        public string ProviderBookingKey { get; set; }
        public Nullable<int> PackageNo { get; set; }
        public string rateClass { get; set; }
        public string rateType { get; set; }
        public string boardCode { get; set; }
        public string childrenAges { get; set; }
        public string paymentType { get; set; }
    }
}
