//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchHotelResult
    {
        public int ID { get; set; }
        public string sID { get; set; }
        public string HotelCode { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public string ProviderHotelCode { get; set; }
        public string ProviderHotelId { get; set; }
        public Nullable<double> CostPrice { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public string SellCurrency { get; set; }
        public Nullable<int> MarkUpID { get; set; }
        public Nullable<double> MarkUpVal { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<double> DiscountVal { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> ResIndex { get; set; }
    }
}
