//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpTSRoomsResult
    {
        public int ID { get; set; }
        public string OptionNo { get; set; }
        public string RoomTypeNo { get; set; }
        public string propertyID { get; set; }
        public string seq { get; set; }
        public string roomTypeID { get; set; }
        public string mealBasisID { get; set; }
        public string roomType { get; set; }
        public string mealBasis { get; set; }
        public Nullable<double> subTotal { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> RSP { get; set; }
        public string ErrataData { get; set; }
        public string provider { get; set; }
        public string bookingToken { get; set; }
        public string sessionID { get; set; }
    }
}
