//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpTSHotelsRate
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> rateTime { get; set; }
        public Nullable<double> rateFrom { get; set; }
        public string availability { get; set; }
        public Nullable<int> runno { get; set; }
        public string refHotelID { get; set; }
        public string hotelID { get; set; }
        public string provider { get; set; }
        public string sessionID { get; set; }
    }
}
