//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpTSRoomsCancelation
    {
        public int ID { get; set; }
        public string optionNo { get; set; }
        public string roomTypeNo { get; set; }
        public Nullable<System.DateTime> ruleFromDate { get; set; }
        public Nullable<System.DateTime> ruleToDate { get; set; }
        public string amendRestricted { get; set; }
        public string cancelRestricted { get; set; }
        public string noShowPolicy { get; set; }
        public Nullable<double> amedCharge { get; set; }
        public Nullable<double> cancelCharge { get; set; }
        public Nullable<double> charge { get; set; }
        public string ruleText { get; set; }
        public string sessionID { get; set; }
        public string cancellationType { get; set; }
        public string markupId { get; set; }
        public Nullable<double> markupAmount { get; set; }
    }
}
