//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpTSRoomsRateDate
    {
        public int ID { get; set; }
        public string optionNo { get; set; }
        public string roomTypeNo { get; set; }
        public Nullable<System.DateTime> rateDate { get; set; }
        public Nullable<double> rate { get; set; }
        public string sessionID { get; set; }
    }
}
